### ISSUE TITLE
加载失败，可能是个假服务器

### ISSUE THREAD

**Issue by moedong** [Jon-Millent/google-proxy#1]
![image](https://user-images.githubusercontent.com/12723410/49706412-c0698180-fc60-11e8-89d5-dc88dbc2f2e8.png)

**Comment by Jon-Millent** [comment]
你的服务器要在香港或者国外才可以使用，另给你个网址可以直接用 www.caup.cn

**Comment by moedong** [comment]
https://github.com/haotian-wang/google-access-helper
